### ISSUE TITLE
mailing not working

### ISSUE THREAD

**Issue by leamasuero** [tylercd100/lern#11]
I followed the instructions but i couldn't make it work. I set it this way:

`config/mail.php`

```
    'driver' => 'log',
    'pretend' => true,

```

I don't know how to troubleshoot this issue since I got no error. On the other hand, exceptions are being recorded successfully in the database.

**Comment by tylercd100** [comment]
Does wrapping it in a try catch produce anything?

``` php
try{
    LERN::handle($e);
} catch (\Exception $ex){
    echo $ex->getFile().":".$ex->getLine()." ".$ex->getMessage()."\n\n".$ex->getTraceAsString();
    die();
}
```

If you do find the error, please let me know about it so I can update the code. Thanks!

**Comment by tylercd100** [comment]
I am working on this right now #12 
Were you able to figure out your issue with using `mail`?

**Comment by leamasuero** [comment]
No. I didn't have time to troubleshoot it. I tried to make this work in the project I'm working on. I was wondering if this issue remains in a fresh new laravel installation.

**Comment by tylercd100** [comment]
Just a heads up
Version `^3.1.2` includes Vincent's changes ( #15 ) for SMTP support and my change ( #12 ) which will actually dump an error instead of giving you an empty response when the Notifier fails. 

If you have time to troubleshoot it please let us know if you find anything :-)
Much appreciated!

**Comment by luciano-masuero** [comment]
Same error. Email not being sent and no error also being triggered.
@tylercd100: Try your code but no Exception being triggered

Laravel: 5.1.27
LERN: 3.1.3

**Comment by tylercd100** [comment]
K I will do some work on this tonight. In the meantime can you please let me know what Versions of Operating Systems you are using? @luciano-masuero @leamasuero

**Comment by luciano-masuero** [comment]
Ubuntu 14.04

**Comment by leamasuero** [comment]
Ubuntu 14.10 (GNU/Linux 3.16.0-23-generic x86_64)

**Comment by jezzdk** [comment]
The log driver doesn't send emails, and having pretend = true suppresses emails as well.
Try using a different mail driver and set pretend to false.

**Comment by luciano-masuero** [comment]
@jezzdk ... I am using smtp driver and is also not sending emails (Just to let you know)

**Comment by vincentmendiola** [comment]
@luciano-masuero are you using gmail for smtp? If so, do you have 2-step verification enabled?

**Comment by luciano-masuero** [comment]
@vincentmendiola ... Yes, I am using gmail smtp and no I do not have 2-step verification

All the other system emails are working normally

**Comment by vincentmendiola** [comment]
@luciano-masuero I was able to get mail sending using the following for the mail environment variables - can you confirm that these match what you have?

```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=address@gmail.com
MAIL_PASSWORD=password
MAIL_ENCRYPTION=ssl
```

I set up a fresh install of Laravel 5.1.27, LERN 3.1.3, and used a gmail account without 2-step verification enabled - the only difference should be our OS.

**Comment by luciano-masuero** [comment]
@vincentmendiola ...

Config:

``` bash
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=email@gmail.com
MAIL_PASSWORD=pass
MAIL_ENCRYPTION=tls
MAIL_FROM_NAME='Testing'
```

Other emails are working
Record of the exception is also working 
Email of the exception is not working

**Comment by luciano-masuero** [comment]
@vincentmendiola ... I have retested and it work

Found some problem on my configs.. So, is working for me right now

**Comment by tylercd100** [comment]
@leamasuero  Can you please try these suggestions so I can close the issue? I'm very curious to see if it fixes the issue with you too. Thanks.

**Comment by tylercd100** [comment]
I am closing this issue. Please open it back up if you are still having trouble.

**Comment by tyler36** [comment]
I'm probably missing something stupid but I can't seem to get the notifications working either.

SETUP: 
Homestead
Laravel 5.2.29
I'm getting the database reporting no problems.
LERN.PHP

```
    'notify' => [
        'channel'                    => 'Tylercd100\LERN',
        'drivers'                    => ['mail'],
...
]
```

In HANDLER.PHP

```
$data = [];
Mail::send('emails.blank',  $data, function ($message) {
                $message->from(env('MAIL_FROM'));
                $message->to(env('MAIL_FROM'));
                $message->subject('control');
            });
try{
    LERN::notify($e);
} catch (\Exception $ex){
    echo $ex->getFile().":".$ex->getLine()." ".$ex->getMessage()."\n\n".$ex->getTraceAsString();
    die();
}
```

If I throw a 404 (visiting a page that doesn't exist), I an entry in my dtabase, & an email from MAIL titled 'control' with either Mailgun or Mailtrap (depending on my current setup. 

I do NOT get a email notification from LERN.

Can't see what I'm missing (but I'm being stupid right?)
