### ISSUE TITLE
Exclude sensitive data

### ISSUE THREAD

**Issue by uyab** [tylercd100/lern#20]
If I set `data => true` in config file, then all input will be posted when exception happen. But what if I want exclude some input data, e.g., password. Would you like to add this functionality?

**Comment by tylercd100** [comment]
We could add a exclude keys option? That could recursively search for certain keys and hide them. Is this something you would want?

**Comment by tylercd100** [comment]
Checkout release [3.2.0](https://github.com/tylercd100/lern/releases/tag/3.2.0) and the excludeKeys options in the [updated config file](https://github.com/tylercd100/lern/blob/3.2.0/config/lern.php)

**Comment by tylercd100** [comment]
It should be noted that this change only affects what is being recorded. If you are using the example from the README to change the notification message then you will need to alter it to ignore the password fields.
