### ISSUE TITLE
Request: Mailgun Integration

### ISSUE THREAD

**Issue by SuperlativeEntity** [tylercd100/lern#29]

**Comment by tylercd100** [comment]
I will see what I can do

**Comment by SuperlativeEntity** [comment]
Thanks Tyler, appreciate your response.

**Comment by tylercd100** [comment]
Please try [v3.5.0](https://github.com/tylercd100/lern/releases/tag/3.5.0) and let me know if you experience any issues!

**Comment by tylercd100** [comment]
Sorry @SuperlativeEntity I had to roll back to v3.4.0. My implementation of mailgun was not working as intended. I will have an update sometime tomorrow.

**Comment by tylercd100** [comment]
Ok, now give [v3.5.0](https://github.com/tylercd100/lern/releases/tag/3.5.0) a try :)

**Comment by SuperlativeEntity** [comment]
Hi @tylercd100, thanks for the update!

I added the following to my .env file:

MAILGUN_TO=mail@test.com
MAILGUN_FROM=test@laravel5.2.com
MAILGUN_APP_TOKEN=key-1234567890
MAILGUN_DOMAIN=sandbox5d118.mailgun.org

Then changed the published config to use mailgun and the exception handler to: LERN::handle($e); in order to record and notify.

The exception logs to the database, the email however does not get sent.

My mailgun settings are in config\services.php, so you might not need to have any config values in the .env file if you look at config\mail.php as well.

**Comment by tylercd100** [comment]
Hmm, can you try setting MAILGUN_FROM to:

MAILGUN_FROM="Test Name test@test.com"

Let me know if that works :)

**Comment by tylercd100** [comment]
Please reopen if you are still having issues with this!
