### ISSUE TITLE
Mail without EOL

### ISSUE THREAD

**Issue by eleftrik** [tylercd100/lern#36]
Hi, just installed your package.
I customized setMessage() as in your example; I receive e-mails, but in the text PHP_EOL gets stripped (in place there is a whitespace), so data are in the same line, without any carriage return.

Even if setMessage() returns something like

```
return "Line 1" . PHP_EOL . PHP_EOL . "Line 2";
```

Am I missing something in the configuration?

Thank you

**Comment by tylercd100** [comment]
Hey @eleftrik version [3.6.4](https://github.com/tylercd100/lern/releases/tag/3.6.4) should fix this issue! Let me know if you are still having issues. :)

**Comment by eleftrik** [comment]
Hi @tylercd100, just upgraded to version 3.6.4, it works!
Thank you a lot for your support
