### ISSUE TITLE
ORA-24816 with Oracle db when collecting user_id

### ISSUE THREAD

**Issue by eleftrik** [tylercd100/lern#37]
Hi, I'm using Laravel 5.3, LERN 3.6.2 and I'm connecting to an Oracle database using yajra/laravel-oci8.

If I set `record.collect.user_id => true` in config/lern.php, I got this issue:
- if the user is authenticated: everything ok
- if the user is not authenticated: when an Exception fires, I got

> RecorderFailedException in Recorder.php line 61: Error Code : 24816
> Error Message : ORA-24816: Expanded non LONG bind data supplied after actual LONG or LOB column
> Position : 12
> Statement : insert into lern_exceptions (class, "file", line, code, message, "trace", user_id, status_code, method, data, url, updated_at, created_at) values (:p0, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10, :p11, :p12) returning id into :p13

If I set `record.collect.userid => false`, everything is ok.

With a mysql database everything works, but unfortunately I have to use Oracle.

The error occurs only when user_id is set to null; if I manually set it to, for example, 0 or -1, there isn't any error.

http://psoug.org/oraerror/ORA-24816.htm

I think user_id column should be the last in the insert query, but I couldn't fix it.

I only found a (bad) workaround: in the model, if the attribute user_id is set to null, I remove it from the model instance, so the database inserts the default value (null) on that column.

Is it possible to fix somehow?

Thank you

**Comment by tylercd100** [comment]
Hey @eleftrik please give [3.6.3](https://github.com/tylercd100/lern/releases/tag/3.6.3) a try and let me know if it works for you!

**Comment by eleftrik** [comment]
@tylercd100: it works perfectly! Thank you
