### ISSUE TITLE
Additional fields?

### ISSUE THREAD

**Issue by eleftrik** [tylercd100/lern#39]
Hi, I would like to add some extra data when logging my exceptions. For example: client IP, user agent, etc.
In my case, I would like to log this information in the db table and notify it via e-mail.
What is the best way?
Thank you.

**Comment by lvian** [comment]
I would second this request, being able to store custom data would be amazing, helping developers to replicate the errors occurred

**Comment by lvian** [comment]
Ok, so I managed to deal with this with a shameful fix, but that solved my problem until some oficial answer.

Basically, inside Handler.php `report function` I add my custom data inside the request fields that are going to be collected if you have `'data'=>true` inside lern.php

Something like this

```
public function report(Exception $e)
{
    Request::merge( 'customFieldKey' => 'customFieldValue' );    
    if ($this->shouldReport($e))
    {
        if (app()->bound("lern")) 
        {
        $erro = app()->make("lern")->handle($e); 
    }
    }
    return parent::report($e);
}
```

**Comment by gthuo** [comment]
Did it my way...like for example to collect IP address I performed these 4 steps.
1. Create a migration that edits the schema lern table to reflect the new columns you want to add, and migrate the changes.

2. On _config/lern.php_, add ip to the list of optional fields, and set it to true on 
![image](https://user-images.githubusercontent.com/13334580/30717028-62d0c51e-9f24-11e7-83c4-617f89d12052.png)

3. On _vendor/tylercd100/lern/src/Recorder.php_, I add ip to the list of $configDependant variables (line 52) 
![image](https://user-images.githubusercontent.com/13334580/30717142-a4800c40-9f24-11e7-94b9-fc86dae13784.png)

4. Still on _Recorder.php_ around line 103 in the **collect()** method, i add the case for ip in the switch statements, just before the **default**
![image](https://user-images.githubusercontent.com/13334580/30717226-e1a35dca-9f24-11e7-868d-99236193e762.png)

4. I add my function defined in 3 above at the end of the file.
![image](https://user-images.githubusercontent.com/13334580/30717260-ff7efbe2-9f24-11e7-9369-0254e95ab6db.png)

And that was all, has been working well!

**Comment by eleftrik** [comment]
@gthuo Yes, but this way you are updating code inside _vendor_ folder. When you update this package, all your modifications will be lost. In my opinion, this is a bad practise.

**Comment by tylercd100** [comment]
Ok good news bad news.

#### Bad news
You're going to need to be on Laravel 5.5

#### Good news:
Version 4.2 gives you:
- An IP address option (There is a new migration) Thank you @gthuo
- Custom Recorder/Notifier classes

In the `config/lern.php`:
```php
'record'=>[
        /**
         * The Recorder to use
         */
        'class' => \App\LERN\CustomRecorder::class,

        'collect' => [
            'user_agent' => true,
            ...
        ]
        ...
],
```

`app\LERN\CustomRecorder.php`
```php
<?php

namespace App\LERN;

use Tylercd100\LERN\Components\Recorder;

class CustomRecorder extends Recorder
{
    protected function collect($key, Exception $e = null) {
        if ($key === "user_agent") {
            return $this->getUserAgent();
        }
        return parent::collect($key, $e);
    }

    protected function getUserAgent() {
        // return user agent string
    }
}
```

And then finally you will need to add a migration for 'user_agent' or any other custom value that you decide to collect

Please reopen the issue if necessary
