### ISSUE TITLE
excludeKeys not working

### ISSUE THREAD

**Issue by sroutier** [tylercd100/lern#42]
The config ```record.excludeKeys``` is not working properly. 

The method ```Recorder.getData()```:
```
    protected function getData() {
        $data = Input::all();
        if (is_array($data)) {
            $this->excludeKeys($data);
            return $data;
        } else {
            return null;
        }
    }
```

Return the unmodified/unfiltered ```$data``` array instead of returning the array modified by ```Recorder.excludeKeys(...)```

PR on its way.

**Comment by tylercd100** [comment]
Version 3.7.5 has this fix

**Comment by sroutier** [comment]
Cool, it's fixed thank you but I can't use it.
I'll open a new issue.
/s
