### ISSUE TITLE
Does not support Laravel 5.1

### ISSUE THREAD

**Issue by sroutier** [tylercd100/lern#44]
The last few releases require Illuminate/support 5.2 which implies Laravel >= 5.2.
Was there a reason to require 5.2? Would you consider lowering the bar to 5.1? I have to keep using 5.1 LTS for a bit.

Thanks.
/S

**Comment by tylercd100** [comment]
Yeah I'm down with lowering it to 5.1.
5.2 was what I was using at the time.

I'll see what I can do tonight

**Comment by sroutier** [comment]
Thanks, if it works it would be appreciated.
/s

**Comment by tylercd100** [comment]
Can you give 3.8.0 a try?

**Comment by tylercd100** [comment]
sorry, try 3.8.1
3.8.0 wasnt actually installing 5.1 oops!

**Comment by sroutier** [comment]
:1st_place_medal: 

Works! Thanks a lot for considering this change, it's really appreciated. Your package is helping me a lot.

Couple of notes in case it helps someone else or even myself next time I encounter these issue:

1) The composer command ran out of memory with this error:
```
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 134217728 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 220
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/composer:0
PHP   2. require() /usr/local/bin/composer:24
...
```

The solution was to unlock the memory limit for that command with:
```
$ php -d memory_limit=-1 /usr/local/bin/composer update tylercd100/lern
```

2) I had to first remove LERN then require it again, otherwise composer would not update it.
```
 $ php -d memory_limit=-1 /usr/local/bin/composer remove tylercd100/lern
 $ php -d memory_limit=-1 /usr/local/bin/composer require tylercd100/lern:^3.8.1
```

My project is getting pretty big with lots of dependencies, so I suppose that composer is not only requiring a lot of memory to process them all, but that it may get a little confused as it does.

Again, thank you very much.
/s
