### ISSUE TITLE
Slack App Token, where to obtain?

### ISSUE THREAD

**Issue by maurocasas** [tylercd100/lern#49]
Hey, I have tried setting my SLACK_APP_TOKEN as the OAuth token, and also using my Client Secret.

How should I proceed? Thanks!

**Comment by tylercd100** [comment]
Hello @maurocasas 

I do not personally use slack with LERN but I do know that we have many users that are currently using it successfully. LERN uses monolog on the backend to connect to various services. You could try going through these links to find a solution.

https://github.com/Seldaek/monolog/issues/743
https://github.com/Seldaek/monolog/issues/514

@loranger, @drjonnicholson, @isomis I know that you guys have mentioned using slack in the issues you've opened up. If you guys have any information on this your help will be most appreciated
