### ISSUE TITLE
Formatting message with release 4.x?

### ISSUE THREAD

**Issue by sroutier** [tylercd100/lern#54]
Hello @tylercd100 ,

With the previous version, I used to format the message using the LERN::setMessage() function.
Is this still supported?

Does not looks to be working for me at the moment.

Cheers.
/S

**Comment by sroutier** [comment]
Got it to work. Just had to make sure that the config option ```view``` in config/lern.php was set to null.
```
...
    'notify'=>[
...
        /**
         * The view file to use
         */
//        'view' => 'exceptions.default',
        'view' => '',
...
```

Perhaps a quick note on the comment to point this out would be helpful.
Great package @tylercd100, Thanks a lot.

/s

**Comment by tylercd100** [comment]
Thank you @sroutier

**Comment by sroutier** [comment]
:+1: 

No, thank you for your great package!

Cheers.
