### ISSUE TITLE
Migrating 3.x to 4.x

### ISSUE THREAD

**Issue by drjonnicholson** [tylercd100/lern#57]
It's worth putting on the readme page that when upgrading from 3.x to 4.x to make sure that the config file now includes the new `lern.notify.class` and `lern.record.class` settings.

Without these we were getting "Class name must be a valid object or a string" reported at line 158 in `LERN.php`. See line 156 and 175 of `LERN.php` for the actual location of the issue.

**Comment by tylercd100** [comment]
Thank you @drjonnicholson

**Comment by tylercd100** [comment]
#58
