### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by tpharaoh** [tylercd100/lern#6]
For some reason in laravel 5.2 the alias in config/app.php wasn't working.

its OK, because I got the package working by writing use Tylercd100\LERN\Facades\LERN as LERN;
in Handler... but just though to write you.

I was getting:
[Sun Mar 27 16:55:50 2016] PHP Fatal error:  Class 'App\Exceptions\LERN' not found in /www/laravelapp/app/Exceptions/Handler.php on line 37

**Comment by tylercd100** [comment]
Looks like you are in the `App\Exceptions` namespace. Try doing `use LERN;` instead of `use Tylercd100\LERN\Facades\LERN as LERN;`
