### ISSUE TITLE
Running on a different DB connection

### ISSUE THREAD

**Issue by leocello** [tylercd100/lern#61]
One of the systems I am working on, has multiple databases. I am having a problem when migrating data to a different database and an exception happens, as LERN tries to save the exception on current database. Is it possible to choose a database for LERN to use?

**Comment by tylercd100** [comment]
Hey @leocello I've got a solution for you. I am adding the config option `lern.recorder.connection`. Please reference the [new config file](https://github.com/tylercd100/lern/blob/master/config/lern.php) and update your local version accordingly. This will allow you to select a different database connection for the model to use. This will be part of the v4.4.0 release

I do not have a multi-database connection to test with so if you could let me know if this works that would be great.

Also, if this solution does not work for your use case please let me know so I can write a better solution.

**Comment by leocello** [comment]
Hey @tylercd100. Awesome! It works fine! Thank you very much.
