### ISSUE TITLE
Compatibility with 6.x

### ISSUE THREAD

**Issue by veakabori** [tylercd100/lern#69]
Hi,
Do you plan to release a new update compatible with Laravel 6.x?

**Comment by tylercd100** [comment]
Yes, I will look into this sometime this week.

**Comment by robbielove** [comment]
Do you have a rough outline of what needs to be done?

Happy to contribute

**Comment by tylercd100** [comment]
Sorry for the extreme delay. LERN v5.0 now supports Laravel 6
