### ISSUE TITLE
Unable to install LERN 5.x package on Laravel 6.x 

### ISSUE THREAD

**Issue by nabeeljavaid** [tylercd100/lern#73]
I am trying to install this package on Laravel 6.8 but getting following composer errors, it seems like something wrong with dependency requirements

Using version ^5.0 for tylercd100/lern
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tylercd100/laravel-notify 3.0.0 requires tylercd100/monolog-mailgun ^2.0 -> satisfiable by tylercd100/monolog-mailgun[2.0.0].
    - tylercd100/lern 5.0.0 requires tylercd100/laravel-notify ^3.0 -> satisfiable by tylercd100/laravel-notify[3.0.0].
    - Installation request for tylercd100/lern ^5.0 -> satisfiable by tylercd100/lern[5.0.0].
    - Conclusion: remove monolog/monolog 2.0.1
    - Conclusion: don't install monolog/monolog 2.0.1
    - tylercd100/monolog-mailgun 2.0.0 requires monolog/monolog ^1.11 -> satisfiable by monolog/monolog[1.11.0, 1.12.0, 1.13.0, 1.13.1, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.17.1, 1.17.2, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.x-dev].
    - Can only install one of: monolog/monolog[1.12.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.13.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.13.1, 2.0.1].
    - Can only install one of: monolog/monolog[1.14.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.15.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.16.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.17.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.17.1, 2.0.1].
    - Can only install one of: monolog/monolog[1.17.2, 2.0.1].
    - Can only install one of: monolog/monolog[1.18.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.18.1, 2.0.1].
    - Can only install one of: monolog/monolog[1.18.2, 2.0.1].
    - Can only install one of: monolog/monolog[1.19.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.20.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.21.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.22.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.22.1, 2.0.1].
    - Can only install one of: monolog/monolog[1.23.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.24.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.25.0, 2.0.1].
    - Can only install one of: monolog/monolog[1.25.1, 2.0.1].
    - Can only install one of: monolog/monolog[1.25.2, 2.0.1].
    - Can only install one of: monolog/monolog[1.25.3, 2.0.1].
    - Can only install one of: monolog/monolog[1.x-dev, 2.0.1].
    - Can only install one of: monolog/monolog[1.11.0, 2.0.1].
    - Installation request for monolog/monolog (locked at 2.0.1) -> satisfiable by monolog/monolog[2.0.1].

**Comment by Eluia** [comment]
This is due to a conflict in requires.

This package (and some of it's dependencies) require monolog/monolog in version ^1.22 while laravel 6 (and ignition) requires monolog/monolog ^1.12 || ^2.0

I managed to fix it for now and install tylercd100/lern in my laravel 6 by forcing a monolog version 1 in my composer.json : 

`"monolog/monolog": "^1.22"`

**Comment by nabeeljavaid** [comment]
should I install "monolog/monolog": "^1.22" in my laravel-6.8 project before installing lern package?

**Comment by Eluia** [comment]
I edited my project's composer.json and added `"monolog/monolog": "^1.22"` in the `require` array.
Then I ran a `composer update`, before installing lern package.
Worked for me on laravel 6.14.0

**Comment by nabeeljavaid** [comment]
@Eluia I don't want to downgrade monolog/monolog, I think tylercd100/lern package should support latest version of monolog/monolog ^2.0 so developers can easily install it on latest version of Laravel without any cumbersome.
THANKS

**Comment by Eluia** [comment]
Same as you, I'd rather run monolog/monolog ^2.0.
Bu until devs fix the packages for laravel 6 and monolog 2 I'll have to run it with monolog 1

**Comment by tylercd100** [comment]
Hey everyone,

I was hoping that updating the version number in the composer.json would be
sufficient to resolve the issue, but there are some needed code changes in
some dependent packages that I also author that need to be fixed first
before this can happen.

Unfortunately, I am moving houses this week and I will have to put this off
until next week.

If anyone wants to fix the dependent packages they are:
https://github.com/tylercd100/monolog-mailgun/pull/2
https://github.com/tylercd100/monolog-sms/pull/5

**Comment by tylercd100** [comment]
I believe the new version adds support for monolog v2
#78
